Synthetixio/kwenta

- package-lock.json
- package.json
- pages/exchange/[[...marketPair]].tsx
- sections/dashboard/CurrencyConvertCard/CurrencyConvertCard.tsx
> fix: upgrade to latst bnc-notify version to fix the bug with the "close" button

- pages/exchange/[[...marketPair]].tsx
> swap base/quote on mobile view

- sections/shared/Layout/Layout.tsx
- styles/media.ts
> hide custom scrollbar on mobile/tablet devices

- .github/workflows/codeql.yml
> ci: add codeql

- tests/lighthouse/lhci-desktop.conf.js
- tests/lighthouse/lhci-mobile.conf.js
> ci: custom lighthouse conf

- .github/workflows/audit_lint_build.yml
> ci: git auth not needed since repo is public

- .github/workflows/audit_lint_build.yml
- .gitignore
- package-lock.json
- package.json
- tests/lint.js
more details:
https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/uploading-a-sarif-file-to-github
> ci: added sarif reports for eslint

- .github/workflows/audit_lint_build.yml
> ci: build-only on feature branches

- .github/dependabot.yml
- .github/workflows/audit_lint_build.yml
> feat: add dependabot for npm (synthetix dependencies only)

- constants/defaults.ts
- containers/Connector/Connector.tsx
- containers/Connector/config.ts
- i18n.ts
- sections/shared/components/LanguageSelect/LanguageSelect.tsx
- store/app/index.ts
- translations/bnc-notify/notifyMessages.ts
- translations/constants.ts
> feat: add missing kr translations

- components/Currency/CurrencyAmount/CurrencyAmount.tsx
- components/ProgressBar/ProgressBar.tsx
- sections/dashboard/SynthBalances/SynthBalanceRow.tsx
- sections/dashboard/SynthBalances/SynthBalances.tsx
> refactor: ui touch ups for synth balances

- .github/workflows/audit_lint_build.yml
> ci: don't run verify stage on pull requests

- .github/workflows/audit_lint_build.yml
- tests/lighthouse/lhci-desktop.conf.js
- tests/lighthouse/lhci-mobile.conf.js
> ci: don't throw lhci errors

- vercel.json
> feat: add caching and security headers

- vercel.json
> fix: remove CSP header

- styles/common.tsx
https://owasp.org/www-community/attacks/Reverse_Tabnabbing
> fix: reverse tabnabbing

- .github/workflows/audit_build_verify.yml
> ci: fix cypress binary path

- package-lock.json
- package.json
new synpress release:
- fix gas fee on testnets
- fix metamask network css selectors
> fix: e2e tests, update synpress to 0.7.1

- pages/shorting/index.tsx
- sections/exchange/FooterCard/TradeSummaryCard/GasPriceSummaryItem.tsx
- sections/exchange/FooterCard/TradeSummaryCard/TradeSummaryCard.tsx
- sections/exchange/FooterCard/common.tsx
- sections/shorting/ShortingRewards/ShortingRewards.tsx
match to design / support mobile view / make it more reusable
> refactor: shorting claim rewards

- components/Currency/CurrencyIcon/CurrencyIcon.tsx
- queries/rates/useExchangeRatesQuery.ts
- sections/shorting/ShortingRewards/ShortingRewards.tsx
> fix(ShortingRewards): use SNX as the reward currency

- components/Currency/CurrencyIcon/CurrencyIcon.tsx
- queries/rates/useExchangeRatesQuery.ts
- sections/shorting/ShortingRewards/ShortingRewards.tsx
This PR contains a pretty major hotfix for the ethereum provider issue #275 
Also, the dynamic icons fix an issue with some of the icons not being loaded correctly (AAVE, REN, etc)
> promote dev to master

- package-lock.json
- package.json
> deps: synpress@0.7.11

- package-lock.json
> ci: fix vercel build issue (package-lock.json issues)

- package-lock.json
- package.json
> deps: synpress@0.7.12

- package-lock.json
- package.json
updates js repo version with support for new chainID types
> fix : Update to support new ChainID string types

- package-lock.json
- package.json
- sections/shared/Layout/AppLayout/Header/ConnectionDot.tsx
- styles/theme/colors.ts
Created a default gold colored dot when connected and if `useOvm=true` then it is used
also removed @synthetixio/js
> feat: Add color for network dot on L2

- sections/shared/Layout/AppLayout/Header/NetworksSwitcher.tsx
- sections/shared/Layout/AppLayout/Header/UserMenu/UserMenu.tsx
- translations/en.json
@vbstreetz I liked the logic you added to the switcher, we'll probably want to bring that back in the future once [EIP-3326](https://github.com/rekmarks/EIPs/blob/3326-create/EIPS/eip-3326.md) is approved.
But for now changed it to a "Switch to L2" button.
> feat: Switch to L2 button

- .github/workflows/audit_build_verify.yml
Changes:
- replace audit-ci with npm audit
- updated docker containers
- removed unnecessary allowed-hosts from lockfile-lint
> ci: update docker containers

- package-lock.json
- queries/collateral/useCollateralShortStats.ts
- sections/shorting/ShortingStats/ShortingStats.tsx
- Updates the weekly snx rewards to be looked up from the rewards contract.
- https://discord.com/channels/413890591840272394/549492529288970251/827537988304764948
> fix: lookup current shorting snx rewards rate & duration from contract

- package-lock.json
- package.json
> deps: update synpress to 0.8.1

- components/PoweredBySynthetix/PoweredBySynthetix.tsx
- components/PoweredBySynthetix/index.ts
- sections/homepage/Benefits/Benefits.tsx
- sections/homepage/Hero/Hero.tsx
- sections/homepage/Steps/Steps.tsx
- sections/shared/Layout/HomeLayout/Footer.tsx
- translations/en.json
Closes: https://github.com/Synthetixio/issues/issues/15
> feat: Homepage Improvements

- sections/shared/modals/SelectTokenModal/SelectTokenModal.tsx
> feat: add "connect wallet" button when the modal opens without being connected

- sections/exchange/hooks/useExchange.tsx
> fix: removes synths from convert currency options

- queries/1inch/use1InchQuoteQuery.ts
- sections/exchange/TradeCard/CurrencyCard/CurrencyCard.tsx
- sections/exchange/hooks/useExchange.tsx
> fix: slippage flashing

- components/Currency/CurrencyIcon/CurrencyIcon.tsx
- constants/queryKeys.ts
- queries/tokenLists/useZapperTokenList.ts
- sections/exchange/hooks/useExchange.tsx
- sections/shared/modals/SelectTokenModal/SelectTokenModal.tsx
- replaced 1inch token list with zapper token list (zapper has over 2000 tokens)
resolves #329
> fix: missing assets on 1Inch convert feature

- constants/currency.ts
- package-lock.json
- sections/exchange/FooterCard/TradeBalancerFooterCard/TradeBalancerFooterCard.tsx
- sections/exchange/TradeCard/MarketDetailsCard/MarketDetailsCard.tsx
- sections/exchange/TradeCard/PriceChartCard/PriceChartCard.tsx
- sections/exchange/hooks/useBalancerExchange.tsx
- sections/exchange/hooks/useExchange.tsx
- sections/shared/modals/BalancerTradeModal/BalancerTradeModal.tsx
- translations/en.json
…#339)
* feat: added support for addtional after-hour stocks
* feat: added support for sCOIN AH
* update assets package version
* update lock
* update the assets package to 2.0.10
* update lock
* include contracts-interface
* add more decimals for krw and jpy
* fix: replace ipfs pool link that has cache issues
* fix: increase pool hop limit
Co-authored-by: AndyTCF <andy.c.f.98@gmail.com>
> feat: support for after hours trading on FAANG

- .github/workflows/audit_build_verify.yml
https://github.com/Synthetixio/issues/issues/60
> ci: invalidate cloudfront cache on release

- pages/dashboard/[[...tab]].tsx
- sections/dashboard/DashboardCard/DashboardCard.tsx
- sections/dashboard/SynthBalances/SynthBalances.tsx
- translations/en.json
fixes https://github.com/Synthetixio/issues/issues/64
> feat: remove 1inch onramp from l2

- sections/exchange/FooterCard/MarketClosureCard/MarketClosureCard.tsx
- sections/exchange/hooks/useExchange.tsx
This reverts commit 47411a018438dad57e4dbc5e01ffdd40aeeb9e3a.
> Revert "feat: disabled sREN temporarily (#389)"

- sections/dashboard/CurrencyConvertCard/CurrencyConvertCard.tsx
- sections/exchange/TradeCard/CurrencyCard/CurrencyCard.tsx
- sections/exchange/hooks/useExchange.tsx
- sections/shared/modals/SelectCurrencyModal/SelectCurrencyModal.tsx
> feat: extended onramp to sETH

- styles/theme/colors.ts
> fix: Readability

- vercel.json
* update config to vercel's default cache-busting value
> fix/temporarily disable /_next/static/(.*) file caching

- vercel.json
This reverts commit f1c1f19dbaea784ff534325959a008b75b23d8c4.
> Revert "fix/temporarily disable /_next/static/(.*) file caching"

- styles/common.tsx
Fixing a left padding issue
**Before:**
**After:**
> fix(styles/CurrencyCard): fix mobile + tablet view styles of CurrencyCard
